import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import companiesRouter from "./companies";
import pipelineRouter from "./pipeline";
import pipelineBoardsRouter from "./pipeline-boards";
import contactsRouter from "./contacts";
import notesRouter from "./notes";
import activitiesRouter from "./activities";
import tasksRouter from "./tasks";
import buyersRouter from "./buyers";
import recyclersRouter from "./recyclers";
import assetsRouter from "./assets";
import bidsRouter from "./bids";
import companyBidsRouter from "./company-bids";
import filesRouter from "./files";
import notificationsRouter from "./notifications";
import dashboardRouter from "./dashboard";
import reportsRouter from "./reports";
import searchRouter from "./search";
import adminRouter from "./admin";
import invitationsRouter from "./invitations";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(companiesRouter);
router.use(pipelineBoardsRouter);
router.use(pipelineRouter);
router.use(contactsRouter);
router.use(notesRouter);
router.use(activitiesRouter);
router.use(tasksRouter);
router.use(buyersRouter);
router.use(recyclersRouter);
router.use(assetsRouter);
router.use(bidsRouter);
router.use(companyBidsRouter);
router.use(filesRouter);
router.use(notificationsRouter);
router.use(dashboardRouter);
router.use(reportsRouter);
router.use(searchRouter);
router.use(adminRouter);
router.use(invitationsRouter);

export default router;
